name: CinemaSafe Buffer

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      text:
        description: Fandango URL
        type: string
        required: true
      startSeat:
        description: Starting Seat
        type: string
        required: true
      endSeat:
        description: Ending Seat
        type: string
        required: true
      

  #Allows this workflow to be called programatically as a downstream tasjk in another workflow
  workflow_call:
    inputs:
      text:
        description: Fandango URL
        type: string
        required: true
      startSeat:
        description: Starting Seat
        type: string
        required: true
      endSeat:
        description: Ending Seat
        type: string
        required: true

jobs:
  cinema-safe:
    name: CinemaSafe
    runs-on: ironman
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CinemaSafe script
        run: |
          echo "Fandango URL: ${{ inputs.text }}"
          echo "Starting Seat: ${{ inputs.startSeat }}"
          echo "Ending Seat: ${{ inputs.endSeat }}"
          node CinemaSafe.js "${{ inputs.text }}" "${{ inputs.startSeat }}" "${{ inputs.endSeat }}"

